### ISSUE TITLE
vitepress error

### ISSUE THREAD

**Issue by byoungd** [wuruoyun/vue-component-lib-starter#30]
env:

`
macOS 12.2
node 14.19.0
Chrome 91
`

run `docs:dev` script

The error info is:

```
Uncaught (in promise) Error: vitepress data not properly injected in app
    at useData (data.js:44:15)
    at setup (index.js:15:26)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7056:29)
    at setupComponent (runtime-core.esm-bundler.js:7012:11)
    at mountComponent (runtime-core.esm-bundler.js:4922:13)
    at processComponent (runtime-core.esm-bundler.js:4897:17)
    at patch (runtime-core.esm-bundler.js:4489:21)
    at render2 (runtime-core.esm-bundler.js:5641:13)
    at mount (runtime-core.esm-bundler.js:3877:25)

```

**Comment by wuruoyun** [comment]
I made a fresh clone, and do get the same error as you saw. However subsequent launch of the docs:dev script no longer show this error. I am not sure what configuration could fix the first-time launch issue, so I will just update README for this for now.
